- .travis.yml
- network/network_test.go
- swupd/swupd_test.go
Fixes Issue: 
Setting to 1.10 get parsed as a float and interrupted as 1.1 instead of 1.10.
See: https://github.com/travis-ci/travis-ci/issues/9247
- Adding quotes so it is treated as a string.
> Fix version of Golang for Travis

- controller/controller.go
- tui/common.go
- tui/menu.go
- tui/network_dialog_check.go
- tui/network_validate.go
- tui/proxy.go
- tui/tui.go
Fixes Issue: #27 
- Switch to using a model PopUp window for Network testing.
- Added URL checking to the Proxy setting
> Network test popup

- controller/controller.go
- tui/network_interface.go
- Do not rerun network test if network known to be passing
- Run Network PopUp testing if any Network Interface is modified
Replaces the open PR #40
> Optimize Network Testing

- .travis.yml
- args/args_test.go
- model/model_test.go
- storage/storage_test.go
- swupd/swupd_test.go
- tests/check-coverage.sh
- tests/coverage-curr-status
This patch fixes the tests coverage regressions and add a small fix
to the script where it doesn't remove the temporary coverage report
file if it fails. Now it can be enabled on the CI and avoid adding
new testsuite regressions.
> testsuite: prepare to enable check-coverage.sh on CI

- tui/common.go
Fixes Issue: #53
- Trap on the Escape-key on the common page type; reacts like the default 'Cancel' key to return to the "previous" page as defined by page setup.
> Enable Escape key to cancel to previous page

- tui/confirm_install.go
- tui/network_dialog_check.go
- Put borders back on the popup windows now that we are borderless
> Enable Borders for PopUp Dialogue windows

- controller/controller.go
- kernel/kernel.go
- model/model.go
- model/model_test.go
- tui/kernel_cmdline.go
- utils/utils.go
We are relying on clr-boot-manager's cmdline-removal feature which
prevents a kernel argument to be added to the boot manager kernel
entry.
Fixes Issue: #18
- Add remove kernel command line argument support
> kernel arguments: add "remove kernel arguments" support

- model/model_test.go
- tests/valid-minimal.yaml
Introduce a minimal valid test, it shows the use of only the required
fields - specially for storage/media configurations.
> model: add a minimal valid test

- .travis.yml
- Makefile
- cmd/cmd.go
- local-travis/local-travis.go
- network/network_test.go
- tests/check-coverage.sh
- tests/coverage-curr-status
- utils/utils.go
This patch introduces the local-travis, an small util program locally
emulate the remote travis execution. The program will read the travis
yaml file and execute the tasks.
The program is not intended to be manually executed but wrapped by
"make local-travis". The program uses the env var TRAVIS_CONFIG to
know where to find the travis yaml file (the makefile will have it all
set for you).
We also use the http_proxy, https_proxy and no_proxy if they are set.
If we're executing a docker command that supports -e flag then these
variables are also handled.
> local-travis: add a travis "emulation"

- .travis.yml
The final build cleanup should be executed on after_script fase, that
way if any tests fails we still have the chance to clean up the build.
> travis: move final clean to after_script

- Makefile
The lint target needs the project is built before actually running
linters, this patch makes the build target dependency of lint target.
> build: add build target as lint dependency

- cmd/cmd.go
- controller/controller.go
- model/model.go
- tests/post-install-sample.sh
- tests/valid-minimal.yaml
Introduce the initial support to post-install hooks. The code also
expands a set of pre-defined variables, for now the only exposed
variable is the chrootDir (the directory where the target system is
mounted).
> post-install: add post-install hooks support

- controller/controller.go
- massinstall/massinstall.go
- model/model.go
- model/model_test.go
- tests/valid-with-version.yaml
The mass-installer use case for image generation requires to specify
the target system version. This patch allows the configuration of
an arbitrary version.
> model: add Version field

- controller/controller.go
- massinstall/massinstall.go
- tui/install.go
Simplify the cleanup code and move the SaveInstallResults() call to
the controller code, removing this knowledge from the front end
implementations.
> controller: simplify cleanup code

- massinstall/massinstall.go
- utils/utils.go
With this we print only the new step getting started - not printing
the actuall progress - if the process is piped/redirected.
> mass installer: print progress only if not piped

- controller/controller.go
- model/model.go
- model/model_test.go
- storage/ops.go
- storage/storage.go
- tests/block-device-image.yaml
- tests/block-devices-alias.yaml
- tests/valid-minimal.yaml
- tests/valid-with-pre-post-hooks.yaml
- utils/utils.go
**This PR includes:**
- block device alias support - users may declare alias and use'em throughout the target media configuration;
- add image support - this is a special alias block device configuration, the controller will setup the loop device and expand the block device's name accordingly
- a small testsuite shuffle
> storage: add block-devices alias support

- args/args.go
Preventing future confusions (when we implement dnf support) rename
the --mirror argument to --swupd-mirror and start creating a namespace
for the arguments.
> args: rename --mirror to --swupd-mirror

- themes/clr-installer.theme
Blue text on black background was noted as hard to read due to lack of contrast.
> Make Disabled Text more readable

- tui/menu.go
If we had configured media for install, and then go back and remove the target media the Install button was left enabled.
> Disable Install on validation fail

- tui/autoupdate.go
- tui/telemetry.go
Two of the Enable/Disable configuration options were assuming Confirm was enabled; otherwise, disable. Escape to cancel should not change the default answer.
> Do not change default for Escape-Cancel

- tui/language.go
Fixes #46
The language code is what is stored in the configuration file and is unmarshalled into the model, the language Tag is left uninitialized. When we find the language code match on initialization, set the language Tag correctly for display in the TUI.
> tui: Fix default Language

- cmd/cmd.go
Commands run through PipeRunAndLog would hang waiting for standard input.
We were overwriting the defined stdin input stream.
> Fix: Pipe Commands Hang

- scripts/installer-image-post.sh
This patch sets the systemd-boot's timeout to 5 so the user may have
the opportunity to change the kernel arguments.
> installer image: set timeout

- args/args.go
- args/args_test.go
- clr-installer/main.go
- cmd/cmd.go
- controller/controller.go
- log/log.go
- log/log_test.go
- storage/ops.go
- storage/storage_test.go
- swupd/swupd.go
- user/user.go
- Changes default log level to Informational
- Remove the unfiltered logging, OUT and replace with Debug or Info
- Cache repeated output lines and report repetition count
- Do not abort on unknown log level
- Allow setting log level via kernel parameter -- likely need to debug installations in the wild
> Change default log level to remove debug data by default

- tests/check-coverage.sh
With this change we check all the tests decreased and print them
all instead of printing the first and exiting.
> check-coverage: print all decreased coverage

- telemetry/telemetry.go
- tui/common.go
Update product name and text on the install screen
> Fix the OS naming

- args/args.go
- clr-installer/main.go
- controller/controller.go
With this argument (either -S or --stub-image) we create the image
- if that's the case - and create the target file systems but don't
actually install content.
It's useful for pre-release validation where the content is generated
and dealt by the release tooling.
> args: add StubImage argument

- Makefile
Fixes: #25 
Use the -race flag to detect/test for race conditions.
> linter: add go build -race

- etc/clr-installer.yaml
SSH Server should be in each install target by default.
> Add open ssh server

- Makefile
If we're installing artifacts to a mock environment for example
the directories like /usr/bin may not exist.
> build: always create dirs

- swupd/swupd.go
If we don't explicitly specify the --keepcache flag the previously
fetch content (specially when using --swupd-state flag) will be
cleaned up and all the content will be downloaded all over again.
> swupd: use --keepcache with "update" command

- controller/controller.go
- etc/clr-installer.yaml
- swupd/swupd.go
- swupd/swupd_test.go
- user/user.go
Be consistent with ister_gui and only add the sysadmin-basic bundle when non-root users are added. Previous we were always adding the sudo bundle.
> Add bundle only when non-root users defined

- .gitignore
- scripts/installer-image.yaml
- Switch to the newly release clr-installer bundle
- Fix a bug where the generated image is removed right after creation
> New bundle name

- args/args.go
- controller/controller.go
- swupd/swupd.go
- swupd/swupd_test.go
Add the swupd's --format, --contenturl and --versionurl arguments.
These arguments are mapped with the --swupd prefix such as:
--swupd-format, --swupd-contenturl and --swupd-versionurl
And are used for constrained environments dealing with local installs,
specially with image generation in a network isolated environment.
> swupd: add new flags

- tests/check-coverage.sh
Sometimes we get coverage reported as an empty string.
This can happen if there is a run time error during execution.
Now dump the contents of the newly generated coverage file
if there is a decrease.
> Dump contents of coverage file on fail

- Makefile
We're considering it to be installed in the .gopath, but actually
we should be using the source dir (scripts).
> build: fix desktop wrapper install

- .travis.yml
To prevent the make install breakage we start also testing the
make install target.
> ci: also validate make install

- scripts/live-desktop.yaml
Reduce the swap partition to 32M with the live-desktop image.
> images: reduce the swap partition

- scripts/live-desktop-post-install.sh
- swupd/swupd.go
- revert the previous full path swupd fix
- write a proper full path swupd fix
- set the required bits to disable gnome lockscreen password
> Live desktop for review

- vendor/github.com/VladimirMarkelov/clui/window.go
Avoid invalid memory address access by no trying to get parent's
control if next control is nil on event processing.
> window: fix event processing

- Makefile
Use the -d argument for install command and let it deal with the
target directory creation.
> build: make sure we let install command create dirs

- scripts/builder.yaml
- swupd/swupd.go
The clear linux OS release process assumes the images build should
be running the same swupd binary across all the build steps, this
patch makes sure we comply with that premise.
> swupd: use the host's swupd

- storage/storage.go
- storage/storage_test.go
lsblk changed their JSON output format for booleans from strings
to actual booleans and for number from strings to actual numbers
in release 2.33.
Updated the code to work with both the new and old formats.
> Update for changes to lsblk

- scripts/developer-image.yaml
Ensure high level of debug logging enabled for developers.
Also view console output on starndard tty to get rescue shell
during boot fails.
> developer: Enable debug logging

- storage/storage.go
This information is actually useless for future references and could
also endup in the telemetry records. Since we have no good reason to
store it we don't want to marshal this data.
> storage: don't unmarshal storage's serial number

- scripts/developer-image-post.sh
- scripts/installer-post.sh
- scripts/installer.yaml
To keep a consistent naming convention, rename installer image.
`[image-name].yaml -> clear-[VER]- [image-name].img.[compression ext]`
> Rename Installer Image

- Readme.md
`installer-image.yaml` was renamed to `installer.yaml` in one of the previous commits.
Updating the Readme to reflect the change.
> Update Readme with new installer.yaml filename

- Gopkg.lock
- Gopkg.toml
- model/model.go
- tests/coverage-curr-status
- utils/utils.go
- vendor/github.com/digitalocean/go-smbios/AUTHORS
- vendor/github.com/digitalocean/go-smbios/LICENSE.md
- vendor/github.com/digitalocean/go-smbios/scripts/license.txt
- vendor/github.com/digitalocean/go-smbios/scripts/licensecheck.sh
- vendor/github.com/digitalocean/go-smbios/smbios/decoder.go
- vendor/github.com/digitalocean/go-smbios/smbios/doc.go
- vendor/github.com/digitalocean/go-smbios/smbios/entrypoint.go
- vendor/github.com/digitalocean/go-smbios/smbios/fuzz.go
- vendor/github.com/digitalocean/go-smbios/smbios/stream_linux.go
- vendor/github.com/digitalocean/go-smbios/smbios/stream_memory.go
- vendor/github.com/digitalocean/go-smbios/smbios/stream_others.go
- vendor/github.com/digitalocean/go-smbios/smbios/stream_unix.go
- vendor/github.com/digitalocean/go-smbios/smbios/stream_windows.go
- vendor/github.com/digitalocean/go-smbios/smbios/structure.go
Fixes Issue: #203
- If running interactively and in a VirtualBox environment force the default to be the kernel-lts.
> Use LTS Kernel for VirtualBox Installs

- args/args.go
- controller/controller.go
- swupd/swupd.go
Fixes Issue: #215
- Allow removing the state directory with new option '--swupd-clean'
> New Option to clean-up swupd state directory

- hostname/hostname_test.go
- log/log_test.go
- scripts/local-telemetry-post.sh
- tests/telemetrics.conf
Update the latest release telemetry configuration file
and update the post install hook with the new default
and the new maximum.
> New telemetry defaults

- scripts/developer-image-desktop-beta.yaml
- scripts/developer-image.yaml
- scripts/enable-installer-post.sh
- scripts/installer-post.sh
- scripts/installer.yaml
When using the --root option with systemctl, libsystemd for the systemd
in the chroot will be resolved on the host.  In cases where the systemd
in the chroot is a different version from the systemd on the host, this
will result in a library not found error.  Need to chroot when eanbling
clr-installer service to avoid this problem.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
Fixes Issue: #249 
- Modify config files to chroot for the systemd command that enables the clr-installer service to avoid using a non-existent libsystemd.
> Chroot when enabling clr-installer service

- scripts/live-desktop-beta.yaml
- Reduce the live desktop beta image size to ensure it fits on an 8GB USB media
> Fix desktop image size for USB media

- Makefile
- clr-installer/gui.go
- clr-installer/main.go
- clr-installer/tui.go
Build two different binaries for the TUI and GUI so
that we do not need to pull along overhead of the GUI
for installations without a graphics environment.
> Split the GUI and TUI

- args/args.go
The initial value will be set incorrectly if the swupd mirror site is set.
> swupd: bug fix for state dir init

- scripts/dump_imports.sh
We use this to review the imported packages are part of our release review process.
> Script for show all imports

- clr-installer/main.go
The command line image generator users common code which requires the locale be set.
> Ensure Locale set for command line and TUI

- Makefile
- args/args.go
- clr-installer/main.go
- controller/controller.go
- iso_templates/initrd_init_template
- iso_templates/isolinux.cfg.template
- isoutils/isoutils.go
- model/model.go
- scripts/live-desktop-beta.yaml
- storage/storage.go
- swupd/swupd.go
- tests/coverage-curr-status
- utils/utils.go
Fixes Issue: #227
- Add `iosutils` package which implements MakeIso() for ISO creation
- Add swupd flag to NOT install bundles beyond os-core
- Add the hook to clr-installer to build ISO files if requested.
ISO generation is based on the script `create-iso.sh`.
Questions:
* What do I do with files that are needed for execution and need to be available on the filesystem?
* Examples are: `isoutils/exclude, isoutils/initrd_init_template, isoutils/isolinux.cfg.template`, and both *.c32 files
* To support a menu on Legacy systems, we need the two files `libutil.c32 and menu.c32`. These files do not exist in Clear Linux at all. The files are currently from a package in Ubuntu. What should we do?
* There's now more prerequisites for clr-installer (but only …
> Add ISO output support

- gui/pages/telemetry.go
Only show notice to request telemetry be enabled for corporate
networks if telemetry server is a private IP like the TUI.
> gui: conditional telemetry message

- args/args.go
- clr-installer/main.go
- syscheck/syscheck.go
Check the system meets Clear Linux's requirements before running
install.
Enable the sysCheck in the default clr-installer.yaml as well.
Currently, this checks for required CPU features and for EFI firmware
(via sysfs).
Fixes Issue: #232 
- Add syscheck package, run by default as part of Install.
Current issues:
- Failure mode is pretty ugly with a Panic message and stack dump
- Tests only EFI firmware and CPU features. No other checks (RAM), can only fail and not warn.
- Failure output could be more descriptive, current looks like "Missing CPU feature: aes"
> Add system compatibility checking

- tui/useradd.go
If we change wording in the GUI we should backport
to the TUI if the same phrase is used.
This will reduce confusion when we enable localization
in the TUI.
> tui: sync working in TUI with GUI

- isoutils/isoutils.go
Change the name of the generated ISO image to be the same as the img
file.
- Remove version string an associated plumbing from isoutils.
- Results in an ISO with the same name as the img (except for extension )
> isoutils: Change name of produced ISO

- tui/tui.go
Fixes Issue: #300
- Attempt to disable console messages before launching the TUI, and re-enable upon completion.
> tui: Disable console messages

- gui/pages/init.go
- gui/pages/telemetry.go
- gui/window.go
Some users were confused by having a Cancel button on the
required Telemetry screen. They assumed if the state was
what they already wanted, they could just Cancel.
We want them to Confirm each time if Telemetry is enabled
or disabled.
> gui: remove cancel button from telemetry

- scripts/live-desktop-post-install.sh
We do not want auto-mounting of media in the installer image
as any mounted media is excluded from possible install targets.
> desktop: disable auto-mounting

- scripts/developer-live-desktop.yaml
Add the NetworkManager and gparted to YAML for now
There should be added to the clr-installer-gui bundle
at release time.
> gui: bundle updates

- Makefile
- etc/clr-installer-gui.desktop
- etc/org.clearlinux.clr-installer-gui.policy
- etc/org.clearlinux.clr-installer-gui.rules
- scripts/live-desktop-post-install.sh
- Made all files and actions consistent with the clr-installer-gui name.
- Fix security of starting Installer; user pkexec not sudo; added new rule for clr-installer-gui.
- Fix bug so only one icon is present when running.
> gui: Desktop Launcher fixes

- scripts/developer-live-desktop.yaml
- scripts/developer-live-server.yaml
For the developer images, we want to disable autoUpdate for the ISO
images.  DevOps always add the version= option which disables
autoUpdate automatically.
> scripts: Disable autoUpdate

- scripts/developer-live-desktop.yaml
The developer image installs the local code over the released
clr-installer bundle. This leaves the old desktop icon for
the TUI. Manually remove for now; it won't be present in the
production release.
> script: Remove extra desktop icon

- storage/storage.go
- Remove the second probing.
- probing only log on fail, do not fail
> storage: remove fatal partprobe

- gui/pages/disk_config.go
Limits the clickable area of the Enable Encryption check button to be
within the label.
> gui: Limit Enable Encryption button click area

- scripts/installer-post.sh
- scripts/ps1-override.sh
- Set the hostname for the live image prompt
Fixes bug where the desktop image terminal has incorrect '#' at the end of the prompt instead of the desired '$'.
> scripts: set prompt via hostname

- tui/install.go
The Partial() function is used to report a partial progress in a
progress bar. When using this function the value set on the progress bar
was always zero since it was doing a division of two integers that were
always resulting in a number < 1 which was being truncated because both
numbers were integers so go was using an integer to store the result
too.
This commit fixes the bug by converting the values to the right types.
Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>
> Fix a bug in Partial truncating an integer value

- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- user/user.go
Recently discovered Clear Linux only allows lower case letter
as part of a login name. Updated validation check and error message.
> user: Only allow lower case letter for login

- controller/controller.go
- gui/pages/install.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Handle errors during installation.
Displays an error message on screen instead of panic and crashing.
This handles the network connectivity error. 
TODO: 
- Get the new strings translated.
- Test for network connectivity on click on Install button before launching the Install screen.
> gui: Handle errors in the Install page

- controller/controller.go
- isoutils/isoutils.go
We need to pass the full suite of options to the ISO
generation code to ensure the call to swupd has all
of the requested options.
> iso: Pass all options through to ISO generation

- iso_templates/initrd_init_template
- iso_templates/isolinux.cfg.template
- isoutils/isoutils.go
Rufus in iso image mode creates a new filesystem and copies all files
from the iso onto that filesystem. This broke Clear boot because there
were missing files from the CD root to boot (those files were in
efiboot.img), and because initrd was limited to mounting only ISO files
to find the rootfs.
Now the files from efiboot.img are copied to the ISO root (so that Rufus
will now work), the initrd paths have been made congruent (though there
are two initrd.gz files - one in efiboot.img and one on the ISO root),
and some extraneous systemd files have been removed.
- Fix Rufus' ISO Image mode
- Make initrd paths on kernel cmdline congruent
- Remove extraneous systemd boot files
This may have a …
> isoutils: Add Rufus ISO image support

- clr-installer/main.go
- gui/window.go
- model/model.go
- tui/common.go
For documentation purposes (screenshots), we do not want to
include the version string. Having a version string in the image
requires updating all image each release.
> tui: gui: Do not display version in Demo mode

- iso_templates/initrd_init_template
- Remove the "Failed" wording in favor of "Searching" during retries as the failed word was confusing to some customers.
- Corrected spelling.
> iso: Change wording of retries

- args/args.go
- gui/gui.go
- network/network.go
- tui/tui.go
Fixes Issue: #233
- Always copy network config during interactive install to target system
- Add command line option to avoid network copy.
> network: Always copy /etc network files

- swupd/swupd.go
Fixes Issue: #380
- Change from --no-scripts to --no-boot-update which will allow post install hooks of swupd to run for the target install.
> swupd: Allow scripts to ensure network changes

- clr-installer/main.go
- gui/common/common.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- syscheck/syscheck.go
- themes/style.css
Run syscheck and report errors after the user chooses their language. This fixes the problem of users booting on Legacy systems and installing on EFI systems to find their system will not boot.
Clear doesn't support Legacy booting beyond the live images, so just return an error and force exiting if EFI isn't found.
Same goes for CPU features, though initrd will refuse to boot if the user is using an ISO image.
Fixes Issue: #232
- Add a syscheck run that executes after clicking 'next' on the localization menu 
- Add a localized dialog box to inform of failures in the chosen language
> Add syscheck and localized error dialog

- Makefile
Update Makefile to avoid GRS check so that it does not behave differently if the source code is in the actual GOPATH.
> Update Makefile to avoid GRS check

- tui/tui.go
Directly after TUI init, run the system check and report if there are
any failures, and force application exit.
Fixes Issue: #232
- Run syscheck when using the TUI front end
- If syscheck fails, report the failure to the user and exit application
> tui: Add error dialog on syscheck failures

- controller/controller.go
- isoutils/isoutils.go
The way this was coded was causing bugs in output when creating an ISO
image. The most obvious was the line "Cleaning up from ISO creation"
would be repeated a few times at the end of execution.
Having sub-progress loops doesn't make sense here, since the flow is
"task"->"completion status" not "task"->"subtask"->"sub
complete"->"task complete"
Also, the removed progress loops would fail to be printed anyways, so
removing them doesn't change progress output except for fixing this
bug.
- Remove a few spurious progress loops and reword some progress strings for clarity
- Removed progress items were bugged anyways and didn't print at all.
output before patch:
```
Saving the installation results …
```
> Fix progress output for ISO generation

- iso_templates/initrd_init_template
Add a main function for init, ensure all locals are labeled with local
correctly, change output to stop abusing kernel warnings.
Change success and failure messages to be consistent with systemd and
more clear to end users.
- Refactor of initrd's init script - lots of comments, a new main() function
- Refactor of output to be consistent with systemd init output
- Stop abusing the kernel messaging system by passing loglevel 1 items to show them on terminals
- Serial terminal won't print messages unless 'quiet' is removed, no workaround I know of. Makes sense that users using serial terminals have enough knowledge to remove 'quiet' I think.
- COLORS
New init output in Legacy when successful: …
> initrd init script: Refactor and add colors

- gui/pages/disk_config.go
- gui/pages/init.go
- gui/window.go
- storage/storage.go
Fixes Issue: #391
In order to avoid delay in loading the installer, scan the media in the
background as a separate go routine.
> Scan Media in the background

- cmd/cmd.go
- controller/controller.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- swupd/swupd.go
- swupd/swupd_test.go
- tui/install.go
Fixes Issue: #12 
When running the "swupd verify" command to install the base OS and the
selected bundles, the progress of the command execution was just being
shown as a progress bar that was looping until the swupd command
finished. This approach was not ideal since this process can take
several minutes to complete, and since the progress bar was just
spinning it didn't provide a real feedback for the user to know in what
part the process was. This can trigger some anxiety in users.
This commit solves this problem by using the machine readable output
from swupd to determine the exact part of the process where the install is
and report this to the user using a series of steps along with a progress
bar (or percentage value in not TUI installer) that shows how far the
step has gotten. …
> Use the JSON output from swupd to report progress

- args/args.go
- isoutils/isoutils.go
- swupd/swupd.go
- tests/coverage-curr-status
Fixes Issue: #228
- Add support for swupd --certpath
- Removed deprecated code
Requires the new release of swupd-client (>= 4.0.0) before the merge.
> Swupd cert

- isoutils/isoutils.go
When the swupd internal API changed, it broke iso production output -
there were progress 'subtasks' again. This commit fixes the output for ISO
creation by moving progress creation until after swupd is finished.
- Don't create a progress until Swupd is done. Not ideal, but still communicates the steps being taken and no longer breaks output
Before:
```
Making squashfs of rootfs [success]
Resolving OS versions [success]initrd [\]
Cleaning up download directory [success]
Downloading required manifests [success]
Resolving files that need to be installed [success]
Downloading required packs [success]alled [\]
Verifying files integrity [success]
Downloading missing files [success]
Installing base OS …
```
> isoutils: Fix output after swupd updates

- gui/pages/install.go
Fixes Issue: #381
This mitigates the crash due to segv faults in the install page.
Please test this at least 5 times to ensure it works.
Fix progess bar segv faults
- Call functions updating the progress bar UI using glib.IdleAdd().
> Fix segv faults in Install page

- gui/pages/init.go
- gui/pages/telemetry.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- tui/telemetry.go
Fixes Issue: #442
- Instead of check box, use buttons to enable/disable telemetry.
- Used simple labels "NO" and "YES" instead of "No, opt-out" and "Yes, opt-in" for precise language translations.
> Enable Telemetry using buttons

- gui/pages/install.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- themes/style.css
Fixes #422.
- Added an info label during installation that indicates success/failure.
- Text wraps the label and makes it selectable.
- Removes the error details from the info msg. Instead, includes the path to the log file.
> gui: Reformat info label during installation

- gui/pages/user_add.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- user/user.go
Fixes Issue: #432
- Re-enable the use of upper case letters for login name
- Now allow dot `.` in the login name
> user: Allow upper case and periods in login name

- controller/controller.go
- model/model.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- Include the name of the hypervisor in the telemetry payload when installed in VM.
Signed-off-by: Alex Jaramillo <alex.v.jaramillo@intel.com>
> telemetry: Include hypervisor to telemetry payload

- gui/pages/init.go
- gui/pages/kernel_options.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- model/model.go
- model/model_test.go
- themes/style.css
- tui/kernel_cmdline.go
Adds a kernel options page to the GUI. Plugs into the back end in a similar manner to the same page on the TUI.
Has a feature for default kernels based on what's loaded in the model already, this means virtualbox installations will by default choose the correct kernel.
Removing more than one flag is problematic, it seems that we just pass the whole value to CBM and it doesn't split strings on space and remove all args.
Fixes Issue: #384, #406
- Add an advanced menu option to modify kernel-related settings
- Page contains a list of all available kernels, highlights and selects the default, adds text to the default name to indicate default status.
- Localization support is added, but still needs to be properly reviewed and properly vetted.
> gui: Kernel options page

- controller/controller.go
Currently, the network check is displayed as success even when it fails.
This fixes the bug to indicate the correct progress status.
> gui: Fix progress bar to indicate correct status

- gui/pages/init.go
- gui/pages/swupd_config.go
- gui/pages/telemetry.go
- gui/pages/user_add.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- swupd/swupd.go
- tui/autoupdate.go
- tui/swupd_mirror.go
- tui/tui.go
Fixes Issue: #405 #407 #455
- Introduces swupd config page that can be used to set Mirror URL and Auto Updates
- Moved associated common GUI and TUI strings to swupd.go
- Added corresponding translations
- Made the change to display swupd related pages in sequence in the TUI menu.
- Fixed resize issue due to long strings in **User Add** page #455 as part of fixing the same for this page.
- Refactored code to handle closing pages due to a bug introduced in this PR.
> gui: Introduces swupd config page

- tests/telemetrics.conf
A new version of telemetrics-client now has built-in defaults for all values and the released configuration file is now all comments as a template. Updating to new configuration file release for checks.
> tests: telemetric update for release 2.2.0

- scripts/InstallerYAMLSyntax.md
The kernel-arguments example is missing a pair of quotes for the remove
field-- without the quotes, two removal entries are added to
cmdline-removal.d on installation: "console=ttyS0" and "115200n8".
The quotes ensure that a single cmdline-removal.d entry,
"console=ttyS0,115200n8", is generated at installation time on the
target.
Signed-off-by: Joe Konno <joe.konno@intel.com>
> InstallerYAMLSyntax: fix cmdline bug in example

- clr-installer/main.go
- gui/pages/swupd_config.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- swupd/swupd.go
- tui/swupd_mirror.go
Fixes Issue: #473
- Return error when swupd-contenturl argument does not use HTTPS or FILE protocol
- Prevent gui/tui from accepting URL that is not the HTTPS or FILE protocol
- Change invalid URL string for gui/tui to suggest HTTPS: "Invalid URL" -> "Invalid URL: Use HTTPS"
- Update locales **(I am not confident in my Chinese translation, so I did not update this)**
- Mixed/Uppercase HTTP and FILE protocols are accepted (Swupd accepts Mixed/Uppercase)
> swupd: Require HTTPS/FILE protocol for mirror

- storage/ops.go
- storage/storage.go
Sort partitions by name in ascending order before writing the partition tables. 
Fixes issue: #237
> storage: Order partitions by name

- isoutils/ISO_README.md
This document has been reviewed by the team, covers what the ISO
generation package does and some of the 'gotchas' when working with
early boot issues. I even had the chance to investigate a boot issue and
document that process while creating this doc.
Fixes Issue: None
- Add ISO_README.md ; the file is in Markdown and renders nicely on Github
-
-
> iso_utils: Add README doc for ISO

- isoutils/isoutils.go
Since clearlinux/clr-bundles@28319f78d1bd ("os-core: Remove content
provided by os-core-plus"), **kmod** package was removed from
os-core bundle and it is shipped by os-core-plus.
Kmod package provides insmod which is used in the ISO initrd/init
script.
Use **os-core-plus** bundle as initrd base instead of os-core.
> isoutils: fix mkInitrd install os-core-plus

- Readme.md
The shell will not expand a `~` when it is proceeded
with an equal sign (`=`). To use `~` in a path, then be
sure to have it preceded by a space.
Fixes: 485
> Remove bug in readme example

- scripts/developer-live-desktop.yaml
- Desktop no longer fits in 7.8GB ; bump to 10GB to match DevOps
> scripts: sync with devops

- clr-installer/main.go
- Bug Fix: Allow --iso=false command line argument to override the value from the YAML file ISO value, and still keep the image file which is created.
> Ensure the image build has results

- iso_templates/initrd_init_template
- syscheck/syscheck.go
We're well into disabling AES as a requirement at this point and have done the needed recompiles. At this point we're needlessly slowing down for little use - AES issues are quickly fixed if found.
> Disable AES checks.

- syscheck/syscheck.go
> syscheck: Fix a spelling error

- language/language.go
- scripts/InstallerYAMLSyntax.md
Fixes Issue: #506
- Updating the installer to use the preferred swupd bundle glibc-locale instead of locales. Both have the same definition.
> locale: switch to swupd bundle glibc-locale

- controller/controller.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
This change executes opt-in when users agree to provide crash information
to the clear linux team and opt-out when users do not agree.
Signed-off-by: Alex Jaramillo <alex.v.jaramillo@intel.com>
> telemetry: execute additional telemetry steps

- controller/controller.go
- model/model.go
- telemetry/telemetry.go
This change removes the need for telemetrics bundle to be present for
the installer to work.
Signed-off-by: Alex Jaramillo <alex.v.jaramillo@intel.com>
> telemetry: do not fail if bundle is not installed

- gui/pages/disk_config.go
The installation type is now preserved when re-entering the disk config
page.
Fixes Issue: No issue filed?
- When selecting an installation type (safe, destructive, advanced) on the GUI disk config page, the selection should be preserved properly.
> gui: Preserve installation type

- Makefile
The `go build -race` command creates an executable with support for race
condition detection, but does not provide any static analysis. This
change adds race condition detection support to the coverage Makefile
target.
Signed-off-by: John Akre <john.w.akre@intel.com>
Fixes Issue: No issue
- Add race condition checking to `make coverage`
> Makefile: Add race condition support to coverage target

- Makefile
The gotk3 package contains deprecated packages that emit a large amount
of warnings during builds. Appending the -Wno-deprecated-declarations
flag to CGO_CFLAGS suppresses these warnings.
Fixes Issue: #539
- Add -Wno-deprecated-declarations option to CGO_CFLAGS in makefile which suppresses the very, very long list of gotk3 deprecated declaration warnings
> Makefile: Suppress deprecation warnings

- storage/ops.go
When sorting partitions, the partition numbers must be separated from
the partition name and be compared as integers. Comparing the partition
numbers in ascii leads to undesirable sorting results when using numbers
with multiple digits.
Fixes Issue: #510
- Improve partition sorting to properly sort partitions with partition numbers > 9
> storage: Sort partition numbers as integers

- clr-installer/main.go
Fixes Issue: #547
- Refactor main so that it is a small function that is only responsible for calling the execute function,
logging failures, and returning the exit status.
- Correctly return error when `encrypt.Crypt` fails
> Refactor main to handle errors without panics 

- controller/controller.go
- scripts/InstallerYAMLSyntax.md
When the version field in the config file is set to 0, the latest
version will be installed instead of the host's version.
Fixes Issue: #502
- The default version is the latest mix version. Previously, the default version was the host's version.
> Update to latest when version is 0

- clr-installer/main.go
- gui/pages/swupd_config.go
- network/network.go
- network/network_test.go
- swupd/swupd.go
- tui/swupd_mirror.go
When passing a config file URL to the --config flag, the installer will
download and consume the config. For example:
clr-installer --config https://pathToConfig.yaml
Signed-off-by: John Akre <john.w.akre@intel.com>
Fixes Issue: #524
- Support URL arguments to --config flag
- Move IsValidMirror to the network package and rename ot IsValidUrl
> Add support to download config over network

- gui/pages/disk_config.go
- storage/storage.go
When using advanced disk partitioning with an invalid setup and loading
the menu page or disk configuration page for the first time, the warning
messages were not set correctly. The warnings were incorrectly set
because the TargetMedias variable was unexpectedly overwritten to nil.
This change prevents unexpected overwrites of TargetMedias and sets
TargetMedias when it is uninitialized.
Fixes: #553
- Correctly set menu disk config warning when incorrectly setting advanced disk partitioning
- Correctly set disk config warning when incorrectly setting advanced disk partitioning
> gui: Correctly set advanced disk config warnings

- tui/menu.go
- tui/user_manager.go
- tui/useradd.go
Fixes Issue: #544
- Move manage user page to required tab in tui
- Add warning and disable confirm button when no admin user is created in tui
- Check the admin button by default for user creation in tui
- Improve logic for ensuring that all required pages are completed in tui
> tui: Secure root user

- utils/utils.go
ExpandVariables was returning early, upon first variable expansion, instead of expanding all available variables.
Also removed unnecessary strings.Contains check as strings.ReplaceAll performs a similar check internally before operating.
Fixes Issue: #579
> Fix early exit in utils.ExpandVariables

- .travis.yml
The docker image used by travis doesn't have telemctl by default any more and telemetry is optional for the installer. This change removes the call to telemctl.
> Remove telemctl from travis

- args/args.go
- args/args_test.go
- clr-installer/main.go
- model/model.go
- scripts/InstallerYAMLSyntax.md
- swupd/swupd.go
Optionally included bundles (also-add) can now be omitted from the
install target by passing the --swupd-skip-optional flag or by setting
the swupdSkipOptional field in the config file.
- Add flag/config field to omit optional bundles from install target
> swupd: Support skipping optional bundles

- etc/systemd/clr-installer-provision.service
- Gate service on configuration file on kernel boot params
> pxe: Block service if no config file

- controller/controller.go
Currently, ISO image generation supports only a single kernel.
Hence, skip ISO generation if multiple kernel bundles are present.
In case the user specifies multiple kernel bundles in the `bundles` config parameter, along with setting the `iso` parameter to true:
- skip ISO generation with a warning message
Signed-off-by: Reagan Lopez <reaganlo@clearlinux-dev-01.jf.intel.com>
> Skip ISO generation if additional kernels are present

- storage/storage.go
- storage/storage_test.go
Fixes Issue: #609
- Parse RAID device types on host system; still not valid for install target
> storage: Add RAID type to known list

- controller/controller.go
- gui/gui.go
- model/model.go
- model/model_test.go
- tui/tui.go
Fixes Issue: #607
- Prevents use of some command-line flags when launching the interactive installer
- Ignore some command-line flags which do not apply to physical media during image generation
> Arg cleanup

- args/args.go
- args/args_test.go
- clr-installer/main.go
- controller/controller.go
- gui/gui.go
- model/model.go
- model/model_test.go
- scripts/InstallerYAMLSyntax.md
- tests/image-generation.yaml
- tui/tui.go
Fixes Issue: #600
- Copy swupd configuration files by default for interactive installs or if set in the YAML configuration file, or via a command-line option.
- Will not copy host /etc/swupd files by default when generating image files.
> Allow skipping swupd configuration file copy

- etc/systemd/clr-installer-provision.service
- Extend delay before starting the installer service
> Remove delay before PXE service

- scripts/InstallerYAMLSyntax.md
- Fixes a couple of typos in the InstallerYAMLSyntax.md
> Docs: Typo fixes for scripts doc

- Gopkg.lock
- Gopkg.toml
- vendor/golang.org/x/sys/unix/syscall_freebsd.go
- vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
- vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
- vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
- vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
- vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
- vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
- vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
- vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
- vendor/golang.org/x/sys/windows/types_windows.go
- Switched to release 1.2.1 instead of tip of master for clui now that the required fix is in a tagger release.
> vendor: update to latest vendor code

- utils/utils.go
Fixes Issue: #634
- Initialize the locale structure to default (English) to ensure all translation calls result in a valid string
> Ensure locale always has a default

- args/args.go
- controller/controller.go
With the new flag we can easily instruct clr-installer to use an arbitrary
build/install, this flag eases the clr-boot-manager's CI by testing image generation
before we land new features.
> args: add --cbm-path

- etc/bundles.json
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Remove the python2 bundle which is no longer valid for Clear Linux OS
> bundles: EOL python2 which has been deprecated

- isoutils/isoutils.go
- model/model.go
- model/model_test.go
- scripts/InstallerYAMLSyntax.md
- tests/iso-bad.yaml
- tests/iso-desktop.yaml
- tests/iso-good.yaml
- Add the publisher and the application/image type to the ISO.
```
$ iso-info live-server.iso
iso-info version 2.1.0 x86_64-generic-linux-gnu
Copyright (c) 2003-2005, 2007-2008, 2011-2015, 2017 R. Bernstein
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
__________________________________
ISO 9660 image: live-server.iso
Application : SERVER
Preparer    : XORRISO-1.5.2 2019.10.26.180001, LIBISOBURN-1.5.2, LIBISOFS-1.5.2, LIBBURN-1.5.2
Publisher   : INTEL CORPORATION
Volume      : CLR_ISO
No Joliet extensions
$ iso-info live-desktop.iso
iso-info version 2.1.0 x86_64-generic-linux-gnu
Copyright (c) 2003-2005, 2007-2008, 2011-2015, 2017 R. Bernstein
This …
```
> ISO: Add metadata to ISO images

- gui/network/network.go
- gui/pages/bundle.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- tui/bundle.go
- tui/confirm_cancel.go
- tui/user_manager.go
Fixes Issue: #635 
- The user used to mistakenly click on items in the additional bundles
page having to wait long duration necessarily if the network did not work.
This provides the user with a warning saying that selecting an additional
bundle requires a working internet connection
>  Additional Bundles Network fix

- log/log_test.go
- model/model_test.go
- backupfile needed to removed as part of model_test.go tests/valid-ister-full-physical-{timestamp}.yaml
- log/archivefile needs to be removed as part of log_test.go
> model, log : Clean test yaml files

- scripts/legacy-kvm-ext4-boot.yaml
- scripts/legacy-kvm-vfat-boot.yaml
These configurations are intended to two different cbm configurations with dedicated
boot partitions either vfat and ext4 formatted.
> scripts: add extra image descriptors

- iso_templates/initrd_init_template
- This removes the `have_vmx`check from the initrd_init template. It originally came from the compatibility-check script for checking compatibility for containers but isn't used by clr-installer as far as I can tell.
> Remove unused have_vmx check from initrd_init

- storage/ops.go
Fixes Issue: #681
- Set the label flag to `-l` for f2fs file systems
> storage: f2fs uses lower case l for labels

- args/args.go
Fixes #683
- Makes the --gui flag hidden
- Refactored the redundant flag hiding logic into a function
> Args: Make --gui flag hidden in help

- massinstall/massinstall.go
- scripts/InstallerYAMLSyntax.md
- storage/ops.go
- storage/storage.go
- tests/coverage-curr-status
Fixes Issue: #628
- Allow the use of the Advanced Media Partition labels with CLI if no targetMedia is found in the YAML file.
> storage: Enable Advanced Media Partition for CLI

- clr-installer/main.go
Fixes Issue: #687
- Changes to non-zero exit status for non-root and mismatched arguments
> Non-zero exit status for error conditions

- cmd/cmd.go
- log/log.go
- storage/ops.go
- storage/storage.go
Fixes several problems in the output of the log file.
- Escaping percent signs
- Wrong format for data type
- Unnecessary format strings
> log: Fix formatting issues in output log file

- args/args.go
- clr-installer/main.go
- controller/controller.go
- gui/gui.go
- gui/pages/disk_config.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- massinstall/massinstall.go
- model/model.go
- model/model_ister.go
- model/model_test.go
- scripts/InstallerYAMLSyntax.md
- storage/block_devices.go
- storage/block_devices_ops.go
- storage/parted_partition.go
- storage/storage_test.go
- storage/swapfile.go
- storage/utils.go
- tui/confirm_install.go
- tui/media_config.go
- tui/tui.go
Fixes Issue: #205
- Changes default from swap partition to /var/swapfile
- Default swapfile size can be overridden via YAML or command line
- Improves media selection logging; why media is not usable
- Relies upon systemd patch to detect and swap on /var/swapfile (since Clear Linux OS 32770)
> Create Swapfile instead of Swap Partition

- controller/controller.go
- storage/block_devices.go
Partially Addresses: #8
- If software RAID is used for one of the target install media, include the bundle with clr-init.
> storage: Include clr-init for software RAID

- completions/bash/clr-installer
- completions/zsh/_clr-installer
- Added `zsh` completion script at `completions/zsh/_clr-installer`. It's
suggested to install it at
`/usr/share/zsh/site-functions/_clr-installer`.
- Added `bash` completion script at `completions/bash/clr-installer`. It's
suggested to install it at
`/usr/share/bash-completion/completions/clr-installer`
Fixes Issue: #711 
---
I invented some tricks with unicode non-printable characters to provide additional functionality not supported by bash builtin completion system:
- line 32-42, will show a help message about the format of the argument to
`--block-device` option, as 
>Format:"alias1:filename1[,alias2:filename2,...]" BlockDevices:${blockdevice:0:-1}"
where `$blockdevice` are generated dynamically. This message won't be
completed.
- line 62-64, will remind the user to use `https://` …
> completions: Added Completions for bash and zsh

- utils/utils.go
- utils/utils_test.go
io.Copy uses a buffer (32 KB), there is no need to read the entire file and allocate large amounts
of memory.
It works faster.
benchmark is available here: [gist](https://gist.github.com/Lasiar/2a4f2f599f9d18f8684e7badbbba110e).
- Changed WriteFile to io.Copy with default size buffer
- Added file.Sync() to ensure file content is written to disk.
> improvement(utils/copyfile): changed writeFile to io.Copy

- .travis.yml
- Makefile
- args/args.go
- clr-installer/main.go
- completions/zsh/_clr-installer
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/block_devices.go
- storage/block_devices_filters.go
- storage/block_devices_ops.go
- storage/storage_test.go
- tests/functional/install/basic.bats
- tests/functional/install/destructive_LVM_RAID_combination.bats
- tests/functional/install/destructive_LVM_across_multiple_disks.bats
- tests/functional/install/destructive_LVM_managed_thinpool.bats
- tests/functional/testlib.bash
- tui/confirm_install.go
Fixes Issue: #633 
- Make sure we present users with ample and concise warnings
- Take action to tear apart layer by layer
- Fail destructive installation if it affects parts of other disks
- Add a force-destructive-install option to allow proceeding with installs which have ill-effects on other disks
> Make destructive install smart 

- boolset/boolset.go
- boolset/boolset_test.go
- clr-installer/main.go
- controller/controller.go
- gui/pages/swupd_config.go
- massinstall/massinstall.go
- model/model.go
- model/model_test.go
- tests/coverage-curr-status
- tui/autoupdate.go
- Add a new type for booleans which should default to true
- Updated the auto-update code
- Auto Update is Disabled when: `autoAupdate: false` in the YAML or if the `version` or `--swupd-version` is set to a value other than `0` or `<current OS version>`
- Auto Update is Enabled by default, or when `autoAupdate: true` set in the YAML regardless of version setting
> Fix Auto update Bug

- model/model.go
- scripts/InstallerYAMLSyntax.md
Documentation and standard convention requires allowInsecureHTTP to be camel-case, but the code and documentation were both incorrect. 
Some users will need to update the YAML files if they already had the incorrect 'AllowInsecureHttp' which is now 'allowInsecureHTTP'.
> Fix case of allowInsecureHTTP for YAML config

- controller/controller.go
- local-travis/local-travis.go
- model/model.go
- network/network.go
- tests/baseline.yaml
- tests/image-generation.yaml
- tests/iso-bad.yaml
- tests/iso-desktop.yaml
- tests/iso-good.yaml
- Enable Strict Unmarshal to ensure that we fail on unknown tokens and duplicate tokens.
> yaml: switch to strict unmarshal

- storage/block_devices_ops.go
- When adding the required options to mkfs for legacy mode on ext, an extra null was being added when options field was empty in the YAML.
> storage: Fix legacy mode mkfs bug

- clr-installer/main.go
- controller/controller.go
- gui/window.go
- swupd/swupd.go
- swupd/swupd_test.go
- tui/confirm_install.go
- tui/menu.go
- utils/utils.go
- Always use offline content by default
- Ensure network check is run before install if offline content won't be used
> Fix usage model for offline content

- clr-installer/main.go
- model/model_ister.go
- model/model_test.go
- tests/coverage-curr-status
- utils/utils.go
- utils/utils_test.go
- Fix how JSON Version field is decoded when reading ister configuration files
- Go 1.14.x now fails json.Number with invalid values
> Fix JSON decoding of ister Version

- Makefile
- args/args.go
- iso_templates/initrd_init_template
- iso_templates/isolinux.cfg.template
- isoutils/isoutils.go
- tests/damage_file.go
> ISO: Add integrity check

- controller/controller.go
- Fix installer hang when clr-boot-manager fails
> controller: Fix hang bug for cbm fails

- isoutils/isoutils.go
- Update the order of loading kernel modules for 5.8 changes
> isoutils: Reorder loadable modules

- isoutils/isoutils.go
- Remove extraneous quotes from DOS label
> isoutils: Remove extraneous double quotes

- isoutils/isoutils.go
ISO creation has been failing because 100M initrd and
the kernel have grown too large for the allocated space.
Eventually we will add this value to yaml config but for
now we will just bump it.
-Update efi partition to 124M from 100M
> Update efi partition to 124M from 100M

- etc/systemd/clr-installer-provision.service
Cleanup for `clr-installer-provision.service`. Trying to avoid extra embedded bash calls -- use systemd's internal capabilties instead of relying on bashisms.
Fixes Issue: #
- Avoid using bash calls as much as possible
- Use systemd's built-in ConditionKernelCommandLine directive to detect clri.descriptor to decide whether to run
- Allow this unit to take over the console (was blocking, attempting askpass, while getty was active)
- Call cat directly to print /etc/issue to console (instead of from bash)
- Call clr-installer directly instead of from a bash loop -- should implement retries via systemd's mechanisms instead
- Call reboot directly as a post action only if/after the installer succeeded
> Let systemd check kernel command line options

- iso_templates/initrd_init_template
initrd calls blkid a few times looking for CLR_ISO, so it can identify the root device that was booted. On each retry, call blkid plain to show everything that's been found -- this may help with debugging boot failures.
> Show found partitions while we're looking for CLR_ISO

- swupd/swupd.go
- telemetry/telemetry.go
- Update the more info URL for telemetry to no longer show a 404 page
- Update the more info URL for auto updating to no longer show a 404 page
> Fix links to external documentation redirecting to 404 pages

- isoutils/isoutils.go
- tests/baseline.yaml
When generating an ISO image, we have a fixed list of kernel modules that should be included. Add logic to determine whether those kernel modules are named `*.ko.zst`, `*.ko.gz`, or `*.ko.xz` instead of only `*.ko`.
> Support compressed kernel modules

- storage/block_devices.go
With increased initrd sizes, 150 MB is inadequate.
See https://github.com/clearlinux/distribution/issues/3192
> Increase default EFI partition size to 512 MB

- isoutils/isoutils.go
ISO initrd is necessarily much bigger than normal initrd, so make sure we have enough space for it.
Fixes Issue: `write /tmp/clrEfi-3358930490/EFI/BOOT/initrd.gz: no space left on device`
-
- bump EFI boot image to 256
> Increase boot partition size for ISO images
