clearlinux/clr-installer

- .travis.yml
- telemetry/telemetry_test.go
Fixes Issue: telemetry testing
- Enable the docker image to bring up systemd for telemetry services
> Fixes to re-enable telemetry testing

- .travis.yml
- Switch to the new Docker image which includes all requirements for testing the installer
> Use the new, faster Docker Image

- etc/clr-installer.yaml
- swupd/swupd.go
- swupd/swupd_test.go
> Add sudo to the core bundle to install

- tui/autoupdate.go
- tui/common.go
- tui/disk_guided.go
- tui/disk_manual.go
- tui/keyboard.go
- tui/language.go
- tui/menu.go
- tui/telemetry.go
- tui/timezone.go
- Another UX review suggestion implemented
> Change Done to Confirm

- tui/menu_button.go
Fixes Issue: #48 
- iconify menu's configuration line
> tui: iconify menu's configuration line

- telemetry/telemetry.go
Fixes Issue: #68
- Switch to using the telemetry package control program
> Use Telemetry control, not system

- storage/storage.go
Ensure when a partition is removed that the remaining
partitions as named properly.
> Properly Remove Partition

- .travis.yml
- clr-installer/main.go
- errors/errors.go
- errors/errors_test.go
- massinstall/massinstall.go
- model/model.go
- tests/basic-valid-descriptor.yaml
- tests/check-coverage.sh
- tests/coverage-curr-status
- tests/real-example.yaml
- tests/valid-network.yaml
- Fixes a small issue with the check-coverage.sh script
- Introduces an specialized error for validation
- Nicely display model validation errors
- Add validation for kernel configuration (kernel config is mandatory)
To test, run mass installer with an invalid configuration (i.e no system language set).
> Errors validation error

- storage/ops.go
- storage/storage.go
With this users may provide custom arbitrary mkfs.* options.
> storage: add options field to block device structure

- controller/controller.go
a quick fix of a missing argument to log format.
> controller: fix a missing format argument

- tui/tab.go
- Allows the left and right arrow keys for Tabs
> Enable Left-Right arrows for Tabs

- crypt/crypt_test.go
- local-travis/local-travis.go
- tests/coverage-curr-status
- crypt: add Crypt() tests
- local-travis: passdown UPDATE_COVERAGE env var
- updated code coverage database
> Tests for review

- tui/common.go
Minor issue found while generating documentation.
> Make Key names consistent

- tui/common.go
- tui/confirm_cancel.go
- tui/disk_config.go
- tui/tui.go
- tui/user_manager.go
- tui/useradd.go
- user/user.go
Improve User account data entry
Fixes Issue: #28
>  Improve User account data entry

- Makefile
- local-travis/local-travis.go
- tests/check-coverage.sh
- add build-local-travis target to Makefile
- add --config flag to local-travis
> Local travis for review

- model/model_test.go
- tests/user-sshkeys.yaml
- user/user.go
Fixes Issue: #74 
- Enable Public Key for new user accounts
- Allow users to be created without password
> Enable Public Key for new user accounts

- model/model.go
This version will be release in parallel with ister_gui for
both validation and identification of any other required features
to release ister.
> Update version for initial release

- scripts/installer-image.yaml
Content has grown with that we need some more space to accommodate
the content.
> installer-image: increase image size

- etc/kernels.json
> Kernel for review

- user/user.go
- Ensure password meet the Linux length requirement
> Set limit for password length

- model/model.go
Update version string to tag a release candidate for 1.0.1
> Release Candidate 1.0.1

- tui/simple_button.go
Fixes Issue: #136
- Ensure we resize SimpleButton type if set to AutoSize
> Resize SimpleButtons

- Makefile
> build: make the desktop file's directory before installing it

- Makefile
> build: fix desktop file's path

- storage/ops.go
- storage/storage.go
- storage/storage_test.go
- Calculate size either at the parent level or as a sum of the children.
- Add error checking and new test cases.
> storage: bug fix for calculating image size

- swupd/swupd.go
> swupd: don't use full path for swupd call

- scripts/live-desktop-beta.yaml
- add beta suffix to live-desktop image
- enable autoupdate on live-desktop image
> Images for review

- scripts/clr-installer-desktop.sh
- Disable the terminal's scrollbar
- Remove the terminal's menu options; including the confusing 'help'
> Update the Clear Installer Terminal

- scripts/installer-image.yaml
- storage/storage.go
- Fix bug in disk size check
- Remove the disk size for the default image in favor of partition sums
> Image sizes

- model/model.go
Fixes Issue: #160
- Update release version
> Release Candidate 1.0.3

- scripts/installer-image.yaml
Fixes Issue: #143 
- Disable modeset and keep the screen resolution consistent across platforms.
> installer-image: set nomodeset

- Makefile
> Only use the release formatted tags

- .travis.yml
- Makefile
- vendor/github.com/atotto/clipboard/go.mod
- vendor/github.com/spf13/pflag/string_to_int.go
- vendor/github.com/spf13/pflag/string_to_string.go
- Fixes bug in vendored files
- Add new test to ensure the integrity of vendored files
> Vendor fixes

- clr-installer/main.go
- controller/controller.go
- storage/storage.go
- storage/storage_test.go
- tests/coverage-curr-status
- utils/utils.go
Change the timing where we check for the root user.
Fixes: 171
> Check for root early

- Makefile
Production builds are made from github source archives. As there
is no repository, git commands will not be available for builds.
> Make make work without git repo

- tui/disk_config.go
- tui/disk_partition.go
Fixes Issue: #179
- Fix initialization bug when adding a new partition in TUI
- Fix bug preventing disabling of encryption once selected in the TUI
> Fix Partitioning Bug

- controller/controller.go
- storage/ops.go
- storage/storage_test.go
- ensure we set the boot mode correctly on the targeted
boot partition
> Set the boot mode on intended partition

- controller/controller.go
- scripts/InstallerYAMLSyntax.md
- Add reference document for YAML Syntax
- Add new environment variable for hooks
> Script support

- controller/controller.go
- storage/storage.go
- Remove Drive Serial Numbers from the clean model (revert the previous solution)
- Remove Network information from the clean model
> Clean telemetry

- controller/controller.go
- telemetry/telemetry.go
- Only archive records when telemetry is enabled
> Only archive records when telemetry is enabled

- scripts/InstallerYAMLSyntax.md
The default version used is the version on the system where the build occurs
> Clarify version used by default

- Readme.md
* Removed 'n' from clearnlinux, should be clearlinux
> docs: Readme.md updates

- user/user.go
Fixes Issue: #209
- Prefix account commands with chroot to ensure using the right version of libraries
> Chroot first, then run useradd

- user/user.go
Fixes Issue: #212 
- Lock root account is any user account has sudo/admin enabled
> Disable the root account if Admin set

- clr-installer/main.go
- controller/controller.go
- log/log.go
- log/log_test.go
- For most installer fails, print a message for the user on submitting a bug
- Provides information for enabling advanced debug logging
- requests sending config and log files
> Crash debug requests

- scripts/developer-image-desktop-beta.yaml
For developer to build a desktop image with the locally
modified installer code.
> Developer Desktop YAML File

- storage/ops.go
- Ensure optimized partition are created
> Ensure proper partition alignment

- Makefile
- scripts/developer-image-post.sh
- Make sure HOME is set for post hook so that GOCACHE is properly set
- New make target to force the re-installation of linters
> Go 1.12 clean up

- controller/controller.go
- hostname/hostname.go
- network/network.go
- network/network_test.go
- tui/network.go
- tui/network_interface.go
- utils/utils.go
Fixes Issue: #230
- Fix setting static IP
> Static IP Fix

- controller/controller.go
- model/model.go
- model/model_test.go
- tui/bundle.go
Fixes Issue: #242
- Remove core/required bundles from visible list
- Add newly selected bundles to the front of the list
> Track user selected bundle separately

- swupd/swupd.go
Fixes Issue: #255
- Run systemctl command in a chroot to avoid compatibility issues
> Chroot systemctl command for disable auto-update

- etc/kernels.json
- Drop the Production Kernel from selection options
- Change LTS kernel to the two supported releases
> Kernel mods

- args/args.go
- args/args_test.go
- clr-installer/main.go
- conf/conf.go
- controller/controller.go
- network/network.go
- network/network_test.go
- tui/install.go
- tui/menu.go
- utils/utils.go
- Download Pre and Post Installer messages
TODO: Display the messages as pop-ups
> Download User Messages

- controller/controller.go
- model/model.go
- scripts/InstallerYAMLSyntax.md
- tui/network_interface.go
Fixes Issue: #261
- Only copying network interfaces when copyNetwork is set to true
> Fix Network Interface Copy

- .travis.yml
- Makefile
- local-travis/local-travis.go
- Exclude the vendor directory from lint commands
- Added new target for lint including vendor for release testing
> Exclude vendor from linting

- gui/banner.go
- tui/tui.go
- utils/utils.go
- Move theme dir function to utils for common use
- Use theme function to find image directory
> Remove hardcoded theme file locations

- Makefile
- gui/banner.go
- gui/contentview.go
- gui/gui.go
- gui/page_header.go
- gui/pages/bundle.go
- gui/pages/disk_config.go
- gui/pages/hostname.go
- gui/pages/init.go
- gui/pages/install.go
- gui/pages/keyboard.go
- gui/pages/language.go
- gui/pages/timezone.go
- gui/summary_widget.go
- gui/switcher.go
- gui/window.go
- themes/style.css
- Introduces new Hostname page
- Uses .css file for styling
- Adds search feature in Language, Keyboard and Timezone pages
- Updates button styles
> gui: Additional gui pages and styling updates

- gui/pages/keyboard.go
- gui/pages/language.go
- gui/pages/timezone.go
- Make the searches look anywhere in the value strings, not just the prefix
> gui: Make the Search filters match anywhere

- gui/pages/bundle.go
Fixes Issue: #242
- GUI version of the same fix that was implemented for the TUI of Issue #242.
> gui: Port of bug fix for Issue: #242

- storage/ops.go
- tui/disk_config.go
- tui/media_config.go
- Rename the manual mode to Advanced Configuration
-
-
> tui: Rename Manual to Advanced

- gui/pages/hostname.go
- gui/pages/init.go
- gui/pages/keyboard.go
- gui/pages/language.go
- gui/pages/timezone.go
- gui/pages/user_add.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- themes/style.css
- Updated code to generate log warnings for trivial errors
- Introduces the new User Add page for adding a single user
- Implements the Delete user feature
> gui: User Add page

- gui/pages/init.go
- gui/pages/user_add.go
- gui/window.go
- Make User Add page as Required
> gui: Make User Add page as Required

- Makefile
- gui/pages/disk_config.go
- gui/window.go
- storage/ops.go
- tui/media_config.go
- Pulls in the TUI changes to the Disk Configuration
> First release of GUI Disk Configuration

- gui/pages/user_add.go
> gui: Minor updates to adduser

- gui/pages/disk_config.go
- gui/pages/hostname.go
- gui/pages/init.go
- gui/pages/telemetry.go
- gui/pages/user_add.go
- gui/window.go
- hostname/hostname.go
- hostname/hostname_test.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- model/model_test.go
- network/network_test.go
- storage/encrypt.go
- storage/storage.go
- storage/storage_test.go
- swupd/swupd_test.go
- telemetry/telemetry_test.go
- themes/style.css
- user/user.go
- Adds the first set of translated strings
- Applies localization to additional strings
- Updates styling and screen size to accommodate translated strings
- Initialize localization in test files
> gui: First translation set

- controller/controller.go
- telemetry/telemetry.go
- Add restart of network systemd services when retesting network
- Security fix to avoid possible endless looping
> Network updates

- etc/clr-installer.desktop
- gui/pages/disk_config.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Handle no media or no safe media edge cases
> gui: Updated to media handling

- gui/pages/user_add.go
- Use the same code to check the password and confirm password.
> gui: Simply password check

- gui/pages/install.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- tui/install.go
All occurrences of Clear Linux* OS should be the same.
> gui: locale: Ensure consistent branding

- gui/pages/init.go
> gui: Fixes bug in text search and entry

- Makefile
- gui/pages/user_add.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Sync the strings across translations so that we can track changes
> gui: Sync the strings across translations

- controller/controller.go
- swupd/swupd.go
- Use new bundle option to swupd verify instead of bundle adds.
- Optimize the flow to only have a single swupd verify call.
> swupd: Speed up install

- scripts/developer-live-desktop.yaml
- Restore c-basic now that the bundle size is resolved
> desktop: Re-add c-basic

- controller/controller.go
- gui/pages/bundle.go
- gui/pages/hostname.go
- gui/pages/install.go
- gui/pages/telemetry.go
- gui/pages/user_add.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/ops.go
- Adds localization for bundle description
- Adds localization for variables
- Removes unsused localization strings
- Adds missing localization strings
- Standardize the strings used for rules
- TODO: Determine if Timezone and Keyboard values should be translated
> gui: Add/update localization strings

- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Remove obsolete strings from localization
> gui: Remove obsolete strings from localization

- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Two are missing from the GUI
Added "Advanced" which is need by the TUI and will be added to the
GUI in the next two weeks.
> locale: Added more strings

- tui/media_config.go
- Fixes a TUI bug for not clearing warning labels
> tui: disk: Fix warning labels

- Makefile
- etc/bundles.json
- gui/pages/bundle.go
- scripts/bundle-check.sh
- swupd/swupd.go
- tests/coverage-curr-status
- tui/bundle.go
- Now validate all optional bundles when building
- Filter bundles which will be installed from the YAML file from optional user selectable bundles
- Remove the bundle name which no longer exists
> Bundle check

- gui/pages/install.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/storage.go
- themes/style.css
- tui/confirm_install.go
- tui/media_config.go
- Prompts user for confirmation before install
- Also disables exit button during installation and re-enables it after installation is complete.
> gui: Prompts user for confirmation before install

- scripts/developer-image-pre.sh
- scripts/live-server-post-install.sh
> scripts: Add missing script and update sytle

- tui/tui.go
Fixes Issue: #300
- Fixes typo in the disable command
> tui: correct typo in dmesg

- isoutils/isoutils.go
isoutils had a bug which would remove additional kernel command line
paramaters specified during image build time.
To fix this, instead of reading the cmdline file from the rootfs,
read the modified cmdline file from the EFI partition (which
clr-boot-manager fills in for us).
Modify the options as required, and then write in the appropriate
places.
- Read the EFI partition from the already-created image, modify as needed, use for new boot systems.
> isoutils: Include custom kernel command line parms

- network/network.go
- Switch from NetworkManager-basic to NetworkManager for the pending network patch set.
- Change to running each systemctl command in sequence instead of as a single command to improve the recovery rate for network restart.
> network: Change in network bundle name

- gui/pages/disk_config.go
- themes/style.css
- Switch from red to a variant of orange
> gui: Change to higher contrast warning color

- tui/disk_config.go
Fixes Issue: #333
- properly propagating flags related to the selected disk
> tui: storage: Advanced Config full disk fix

- controller/controller.go
- gui/common/common.go
- gui/pages/disk_config.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/storage.go
- themes/style.css
- tui/popup_passphrase.go
- gui: Introduce common functions for Dialog (popup)
- gui: Re-implements Install confirmation based on common dialog functions
- gui: Implements disk encryption
TODO: encryption passphrase visibility mode
> Install Confirmation and Disk Encryption

- clr-installer/main.go
- Create a simple lock file for preventing more than one instances of the installer from running.
> Prevent duplicate instances

- etc/clr-installer-gui.desktop
- gui/pages/disk_config.go
- gui/pages/hostname.go
- gui/pages/init.go
- gui/pages/user_add.go
- hostname/hostname.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- network/network.go
gui: Add second set of translations
> gui: Add second set of translations

- controller/controller.go
- gui/pages/disk_config.go
- gui/pages/user_add.go
- gui/window.go
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Add the third set of translations and optimize screen size further.
> gui: Add third set of translations

- gui/pages/user_add.go
- Force the only user to be an admin
- Remove the delete button; delete will be in the upcoming user manager
- Several logic fixes
Known Bug:
- Changing the password and it has already been set once will crash the application
> Gui user fixes

- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
Add translation fixes from localization team
> gui: Add translation fixes from localization team

- tui/install.go
- Forward port TUI fix for multi-step progress
> Fix a bug in Partial truncating an integer value

- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
> Network handling translation

- Makefile
- Fix remove paths in Makefile
> Update makefile for correct remove paths

- scripts/developer-live-desktop.yaml
- scripts/developer-live-server.yaml
- scripts/live-desktop-post-install.sh
- Add the software store icon to the desktop toolbar in the live image
- Update the developer configuration YAML to be in-sync with DevOps
> Add Software Store to Toolbar

- locale/es_MX/LC_MESSAGES/clr-installer.po
Localization of the thank you message read clearer in Spanish with the newlines suggested.
> locale: Re-insert newlines

- etc/clr-desktop.yaml
- scripts/developer-live-desktop.yaml
- Now also include vlc to every desktop install.
> gui: Added vlc to default installed bundles

- Gopkg.lock
- Gopkg.toml
- clr-installer/main.go
- vendor/github.com/nightlyone/lockfile/.gitignore
- vendor/github.com/nightlyone/lockfile/.gitmodules
- vendor/github.com/nightlyone/lockfile/.travis.yml
- vendor/github.com/nightlyone/lockfile/LICENSE
- vendor/github.com/nightlyone/lockfile/README.md
- vendor/github.com/nightlyone/lockfile/appveyor.yml
- vendor/github.com/nightlyone/lockfile/lockfile.go
- vendor/github.com/nightlyone/lockfile/lockfile_unix.go
- vendor/github.com/nightlyone/lockfile/lockfile_windows.go
Fixes Issue: #364
- Enable process based locks to enable checking and recovery
- Use lock files based on the log file to enable concurrent executions (of image generation)
> Base the lock file on the log file

- gui/pages/disk_config.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- syscheck/syscheck.go
- gui: Add popup dialog for rescan media
- Remove hardcoding filename in localization files
> Rescan popup

- Readme.md
- minor updates due to GUI and ISO images
> readme: minor updates due to GUI and ISO images

- .travis.yml
- Workaround to handle a change in swupd in Docker images under non-clear OSes
> travis: Add workaround for swupd issue

- .travis.yml
- Clean up TravisCI file now that the Docker image is updated for gtk dev
> travis: Docker image updated for gtk3

- scripts/InstallerYAMLSyntax.md
- Add details about using the rest of the free space.
> doc: YAML information update

- args/args.go
- args/args_test.go
- Default to debug logging level
> log: Change default to debug logging

- gui/pages/telemetry.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- tui/menu.go
- tui/telemetry.go
- Make the text more clear about the data which might be shared
- Change default to "No choice made" to make it more clear that Telemetry must be visited
> Update Telemetry wording

- gui/pages/telemetry.go
Fixes #446
Make telemetry label selectable
> gui: Make telemetry label selectable

- controller/controller.go
- gui/common/common.go
- gui/pages/disk_config.go
- gui/pages/init.go
- gui/pages/install_widget.go
- gui/pages/language.go
- gui/pages/pre_check.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- syscheck/syscheck.go
Fixes Issue: #416
- After the language is selected, the pre-check page checks if the prerequisites for the installation are met. Currently the checks include system compatibility and network connectivity.
- Fixes the progress failure status to show a different color.
- Refactored to remove redundant code.
- Displays the system check error.
> Pre-Check page

- gui/common/common.go
- gui/gui.go
- gui/pages/init.go
- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- log/log.go
- log/log_test.go
- themes/style.css
Fixes Issue: #417
- Introduces Panic() to handle crashes
- Removed "model" and "installReboot" variables from Gui struct as they are not being used.
- Updated log level from warning to errors wherever applicable.
> Handle crashes

- storage/storage.go
- tests/telemetrics.conf
Fixes Issue: #468 and based on my testing, will allow creating images on AWS/EBS-backed volumes.
> Support installing on 'Connected' block devices

- clr-installer/main.go
Fixes Issue: #463 
- Replace os.Exit with fatal
- Add error channel for goroutines in main.go
- Remove unused unlock code from fatal function
> Execute deferred functions during failure

- gui/pages/disk_config.go
- themes/style.css
Implements #404
Make the Media Selection title clickable
> gui: Make the Media Selection title clickable

- locale/zh_CN/LC_MESSAGES/clr-installer.po
> Fix Chinese translation for the word "letter"

- etc/kernels.json
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Fix phrasing and translation for kernel native bundle
> locale: Fix phrasing and translation for kernel

- scripts/InstallerYAMLSyntax.md
Fixes Issue: #501
- Document new options for images
> Update YAML Syntax for ISO files

- tui/media_config.go
Fixes Issue: #541
- Bug fix for using encryption
> tui: Fix encryption enable bug

- args/args.go
- args/args_test.go
- clr-installer/main.go
- controller/controller.go
- gui/pages/swupd_config.go
- isoutils/isoutils.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- model/model.go
- scripts/InstallerYAMLSyntax.md
- swupd/swupd.go
- swupd/swupd_test.go
- tui/swupd_mirror.go
Fixes Issue: #478
- Support insecure updates over HTTP
- swupd: identify certificate errors
- Ensure we default to software auto update for UI
> Add Support for insecure updates over HTTP

- gui/window.go
- attempt to use monitor relative size to the installer window if primary monitor found
- pack window.contentLayout to a scrolledwindow to ensure user is able to complete installation with low resolution monitor
> scalable installer window, scrollable content

- clr-installer/main.go
- network/network.go
- Fix bug where relative/absolute config file paths were rejected
- Add HTTP warning when using HTTP URI without seeing --allow-insecure-http
> Config bugfix

- controller/controller.go
- isoutils/isoutils.go
- swupd/swupd.go
- swupd/swupd_test.go
- Refactor swupd regarding the use of model
- Required for future argument improvements
> swupd: Refactor name of swupd command

- args/args.go
- args/args_test.go
- clr-installer/main.go
- Add a single command-line argument for swupd URLs
> args: Enable --swupd-url for shorthand

- Makefile
Fixes Issue: #527 
- Replace gometalinter with golangci-lint
> Replace gometalinter with golangci-lint

- clr-installer/main.go
- model/model.go
- scripts/InstallerYAMLSyntax.md
- swupd/swupd.go
Fixes Issue: #559
- Allow the format to be set in the configuration YAML file as well as on the command line.
> swupd: model: Allow format to be set in config

- tui/bundle.go
- This is the only menu option not in Title Case.
> tui: Fix Title Case

- args/args.go
- args/args_test.go
- clr-installer/main.go
- Allow setting swupd version on the command line
> Swupd version via command line

- tui/media_config.go
- Fixed bug where the media was not complete for advance disk configuration
> tui: Set done when media selected

- tests/coverage-curr-status
- utils/utils.go
- utils/utils_test.go
- Add the first test for utils coverage
> Utils coverage

- controller/controller.go
- gui/network_dialog_check.go
- gui/pages/install.go
- isoutils/isoutils.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- massinstall/massinstall.go
- progress/progress.go
- storage/ops.go
- storage/storage_test.go
- swupd/swupd.go
- swupd/swupd_test.go
- tui/install.go
- tui/network_dialog_check.go
Fixes Issue: #516
- Create indeterminate progress bar when swupd StepCompletion == -1
- Add new swupd installation steps
- Add printPrefix to NewLooP()
> Support swupd indeterminate progress bar

- swupd/swupd.go
- swupd/swupd_test.go
- Remove totalSteps to align with swupd removal clearlinux/swupd-client#1142
> swupd: Remove totalSteps from JSON

- Makefile
- mixer/release-image-config.yaml
- Add template file for mixer to enable clr-installer as the build tool.
> mixer: Add image template for use by mixer

- Makefile
- args/args.go
- clr-installer/main.go
- controller/controller.go
- etc/systemd/clr-installer-provision.service
- massinstall/massinstall.go
- tests/coverage-curr-status
NOT READY FOR MERGE -- testing phase
Fixes Issue: #591
- Add a new service file for PXE installs
- Add retries to download the configuration file
- Properly enable automatic reboots
> PXE Enablement changes

- scripts/add-pxe-issue.sh
- scripts/pxe.yaml
- Add reference script to generate pxe image. This image can be processed to create initrd.
> scripts: Add pxe reference script

- scripts/add-desktop-login-issue.sh
- scripts/add-login-issue.sh
- scripts/add-server-login-issue.sh
- Public link changed; update sample YAML configs
> scripts: Community link moved

- controller/controller.go
- model/model.go
- model/model_test.go
- New interactive restrictions should not have included --keep-image
> model: controller: Keep Image default

- storage/ops.go
- storage/storage.go
Fixes Issue: #616
- Does a recursive search for mounted children
> Check all children of a block device for mounted partitions

- tests/image-generation.yaml
- Fix test case variable case from PR#621
> Fix test case variable case

- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/ops.go
- storage/storage.go
Fixes Issue: #623
- Remove logical partitions when destructive install of whole disk
> storage: remove logical volumes during wipe

- .travis.yml
- cmd/cmd.go
- controller/controller.go
- gui/window.go
- storage/ops.go
Fixes Issue: #447
- Add which system requirement failed using system check
- Ensure all fail reason are passed back to UI
- Ensure GUI denotes the step with a fail icon
> Provide fail reasons

- Makefile
- args/args.go
- args/args_test.go
- themes/clr-installer.theme
- themes/high-contrast.theme
- tui/confirm_install.go
- tui/install.go
- tui/network_dialog_check.go
- tui/tui.go
Fixes Issue: #217
- Black and white theme to improve contrast
> tui: high-contrast theme

- model/model_test.go
- clean up generated YAML files
> model: clean up generated YAML files

- scripts/aws.yaml
- scripts/azure-docker.yaml
- scripts/azure-machine-learning.yaml
- scripts/azure.yaml
- scripts/builder.yaml
- scripts/cloud-docker.yaml
- scripts/cloud.yaml
- scripts/containers.yaml
- scripts/developer-image.yaml
- scripts/developer-live-desktop.yaml
- scripts/developer-live-server.yaml
- scripts/gce.yaml
- scripts/hyperv-mini.yaml
- scripts/hyperv-test.yaml
- scripts/hyperv.yaml
- scripts/installer.yaml
- scripts/kvm.yaml
- scripts/legacy-kvm.yaml
- scripts/live-docker.yaml
- scripts/live.yaml
- scripts/pxe.yaml
- scripts/service-os.yaml
- scripts/vmware.yaml
- tests/baseline.yaml
- tests/image-generation.yaml
- tests/iso-bad.yaml
- tests/iso-desktop.yaml
- tests/iso-good.yaml
Also capitalize/end with period.
> Typo in YAML scripts

- controller/controller.go
Fixes Issue: #649
- Enable networking (DNS) in chrooted environment for post-install hooks.
> controller: Enable networking in a chroot

- swupd/swupd.go
Fixes Issue: #667
- Update swupd info URL
> swupd: Fix URL which was broken

- gui/window.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- storage/ops.go
- storage/storage.go
- syscheck/syscheck.go
- tui/confirm_install.go
- tui/tui.go
- utils/utils.go
Fixes Issue: #517
- Remove the requirement for UEFI booted system (Replaces #655)
> Remove UEFI requirement

- Makefile
- Fix to the makefile outside of git repo
> Fix to the makefile outside of git repo

- controller/controller.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Add a final step that confirms for the user that the installation has completed.
> Add complete step to the task list

- etc/kernels.json
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Add newest lts kernel to choose list
> kernel: Add new lts2019 kernel option

- swupd/swupd.go
- Fix some minor typos in comments found while working on other changes
> swupd: fix comments

- conf/conf.go
> conf: drop unused constant

- storage/storage.go
- storage/storage_test.go
1.) Move some code to test so that they are not part of executable
2.) Remove unused code
#530 
1.) Move some code to test so that they are not part of executable
2.) Remove unused code
> Cleanup of storage code

- controller/controller.go
- model/model.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
- Prevent telemetry error in the log file when not present.
> telemetry: Prevent error when not present

- args/args.go
- args/args_test.go
- clr-installer/main.go
- controller/controller.go
- gui/pages/disk_config.go
- isoutils/isoutils.go
- massinstall/massinstall.go
- model/model.go
- model/model_test.go
- scripts/InstallerYAMLSyntax.md
- storage/encrypt.go
- storage/ops.go
- storage/storage.go
- tests/coverage-curr-status
- tui/media_config.go
- tui/tui.go
Fixes Issue: #517
- Enable new override functionality for media size
- Refactor and simply partition validation code
- Update partitioning support in legacy mode
> Refactor disk validation

- etc/kernels.json
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- Only offer the latest LTS kernel as an alternative
> kernel: Drop extra LTS kernels

- Makefile
- tests/check-all-images.sh
- New validation/QA code to attempt to build all images published by our DevOps
> tests: Add new test to build all DevOps Images

- Makefile
- clr-installer/main.go
- controller/controller.go
- gui/pages/disk_config.go
- storage/parse.go
- Instead of skipping whole files, just exclude the few complex functions.
> lint: Only ignore the few problem functions

- storage/block_devices.go
- storage/block_devices_filters.go
- storage/block_devices_ops.go
- Remove unused functions
- Create a filter function which can help with querying of block devices which satisfy certain conditions
- Abstract away Partitioning logic for gparted to reduce cyclomatic complexity for WritePartitionTable
> Storage Refactor: Add blockdevices filters, Abstraction on looping, Abstract partition using parted 

- storage/block_devices_ops.go
- fix comment and logging message
> storage: fix comment and logging message

- tests/check-all-images.sh
- Enable use of mirror URL for image testing
> tests: Enable use of mirror URL for image testing

- tests/check-all-images.sh
- Fix bug with passing the URL
- Added debug hook for no cleanup on success
> tests: Fix bug with passing the URL

- clr-installer/main.go
Fixes #568
Reduced high 80s score to lower than 30
- Factor execute function into much smaller functions  this reducing cyclomatic complexity
> Fix gocyclo complexity of main.go

- storage/block_devices_ops.go
Partially Addresses : #8 
- In Advanced partitioning flow, allow the use of raid devices as targets for installation. Make sure that boot partition needs to be on non-raid device and non-lvm device
> Support software raid in Advanced partitioning flow

- Makefile
- completions/bash/clr-installer
- Add new completion files to the install step
- Add short flags to the bash completion
> Completion Updates

- controller/controller.go
- locale/en_US/LC_MESSAGES/clr-installer.po
- locale/es_MX/LC_MESSAGES/clr-installer.po
- locale/zh_CN/LC_MESSAGES/clr-installer.po
- massinstall/massinstall.go
- storage/block_devices_ops.go
- storage/storage_test.go
- Fixes a problem where the boot partition may not be set correctly if boot and root are on different media.
- Add missing translation
> Fix setting the boot partition

- .travis.yml
- Makefile
- tests/basic.yaml
- tests/functional/install/basic.bats
- tests/functional/testlib.bash
Signed-off-by: Karthik Prabhu Vinod <karthik.prabhu.vinod@intel.com
Fixes Issue: #710 
Adding a BAT based funcitonal testing framework
Add targets make functional to makefile and .travis.yml
> testing: Add functional testing

- .travis.yml
- Retry installing linter if it fails
> Makefile: Add retry to install linters

- Makefile
Add a new target for devs to test their commits.
> Makefile: Add a dev-check-all target

- massinstall/massinstall.go
- Exit with non-zero on validation error for mass installer
> massinstall: Exit with error for validation fails

- storage/block_devices.go
- storage/block_devices_ops.go
- storage/storage_test.go
- Fix logic error for skipping validation check
- Allow forced override of /boot as ext
> storage: Validation fix

- scripts/kvm-swapfile.yaml
- storage/block_devices_ops.go
- Fix logic bug for swapfile size and 0 size for root in YAML
> storage: Fix bug in swapfile checking

- Makefile
- model/model.go
- model/model_ister.go
- model/model_test.go
- tests/check-json-yaml.sh
- Fix bug in the JSON to YAML conversion
- Add new test script and make target
> Model init fix

- Readme.md
- Add reference to the clr-installer-dev bundle
> README: Add a reference to clr-installer-dev bundle

- controller/controller.go
- Fix bug where we add a log comment about ignoring offline content when it may not be present to ignore
> controller: Offline content ignore

- controller/controller.go
- scripts/InstallerYAMLSyntax.md
- storage/block_devices.go
- storage/block_devices_ops.go
- storage/parse.go
- tests/advanced.yaml
- tests/functional/install/lvm_advanced.bats
Fixes Issue: #8 
- Enable the use of LVM for root partition during installation
- Allow additional Advanced Installation partitions to be logical volumes (UNDER DEBUG)
> Enable lvm root

- how-to-make-a-release
Signed-off-by: William Douglas <william.douglas@intel.com>
Fixes Issue: #
-
-
-
> Add release process document

- isoutils/isoutils.go
-Bump efi part from 150M to 192M
> Bump efi part from 150M to 192M

- .github/workflows/golangci-lint.yml
> Update golint workflow
